export { Sonzai } from "./client.js";
export { VoiceStreamInstance } from "./resources/voice.js";

// Errors
export {
  SonzaiError,
  AuthenticationError,
  NotFoundError,
  BadRequestError,
  PermissionDeniedError,
  RateLimitError,
  InternalServerError,
  APIError,
  StreamError,
} from "./errors.js";

// Types
export type {
  // Config
  SonzaiConfig,
  // Agent CRUD
  Agent,
  CreateAgentOptions,
  UpdateAgentOptions,
  SDKPersonalityDimensions,
  Big5Scores,
  AgentToolCapabilities,
  SeedMemory,
  // Chat
  ChatMessage,
  ChatChoice,
  ChatUsage,
  ChatStreamEvent,
  ChatResponse,
  ChatOptions,
  // Dialogue
  DialogueOptions,
  DialogueResponse,
  // Events
  TriggerEventOptions,
  TriggerEventResponse,
  // Memory
  MemoryNode,
  AtomicFact,
  MemoryResponse,
  MemorySearchResult,
  MemorySearchResponse,
  TimelineSession,
  MemoryTimelineResponse,
  MemoryListOptions,
  MemorySearchOptions,
  MemoryTimelineOptions,
  Fact,
  FactListResponse,
  FactListOptions,
  MemoryResetOptions,
  MemoryResetResponse,
  SeedMemoriesOptions,
  SeedMemoriesResponse,
  // Personality
  Big5Trait,
  Big5,
  PersonalityDimensions,
  PersonalityPreferences,
  PersonalityBehaviors,
  PersonalityProfile,
  PersonalityDelta,
  PersonalityResponse,
  PersonalityGetOptions,
  PersonalityUpdateOptions,
  PersonalityUpdateResponse,
  // Sessions
  SessionStartOptions,
  SessionEndOptions,
  SessionResponse,
  // Instances
  AgentInstance,
  InstanceListResponse,
  InstanceCreateOptions,
  // Notifications
  Notification,
  NotificationListResponse,
  NotificationListOptions,
  // Context data
  ContextDataOptions,
  MoodResponse,
  MoodAggregateResponse,
  RelationshipResponse,
  HabitsResponse,
  Goal,
  GoalType,
  GoalStatus,
  GoalPriority,
  GoalsResponse,
  CreateGoalOptions,
  UpdateGoalOptions,
  DeleteGoalOptions,
  InitialGoal,
  InterestsResponse,
  DiaryResponse,
  UsersResponse,
  ConstellationResponse,
  BreakthroughsResponse,
  WakeupsResponse,
  // Tool definitions
  ToolDefinition,
  // Voice
  VoiceStreamToken,
  VoiceTokenOptions,
  VoiceStreamEvent,
  VoiceUsage,
  VoiceEntry,
  VoiceListResponse,
  VoiceListOptions,
  // Generation
  GenerateBioOptions,
  GenerateBioResponse,
  GenerateCharacterOptions,
  GenerateCharacterResponse,
  GeneratedGoal,
  SDKInteractionPreferences,
  SDKBehavioralTraits,
  GenerateSeedMemoriesOptions,
  GenerateSeedMemoriesResponse,
  LoreGenerationContext,
  IdentityMemory,
  ImageGenerateOptions,
  ImageGenerateResponse,
  // Custom States
  CustomState,
  CustomStateListOptions,
  CustomStateCreateOptions,
  CustomStateUpdateOptions,
  CustomStateListResponse,
  CustomStateUpsertOptions,
  CustomStateGetByKeyOptions,
  CustomStateDeleteByKeyOptions,
  // Wakeups
  ScheduleWakeupOptions,
  ScheduledWakeup,
  // Webhooks
  WebhookEndpoint,
  WebhookRegisterOptions,
  WebhookRegisterResponse,
  WebhookListResponse,
  WebhookDeliveryAttempt,
  DeliveryAttemptsResponse,
  // Evaluation
  EvalCategory,
  EvaluationResult,
  EvaluateOptions,
  // Simulation
  SimulationEvent,
  SimulationSession,
  UserPersona,
  SimulationConfig,
  SimulateOptions,
  RunEvalOptions,
  EvalOnlyOptions,
  RunRef,
  // Eval templates
  EvalTemplateCategory,
  EvalTemplate,
  EvalTemplateListResponse,
  EvalTemplateCreateOptions,
  EvalTemplateUpdateOptions,
  // Eval runs
  EvalRun,
  EvalRunListResponse,
  EvalRunListOptions,
  // Agent list
  AgentListOptions,
  AgentIndex,
  AgentListResponse,
  // Batch personality
  BatchPersonalityEntry,
  BatchPersonalityResponse,
  // Session tools
  SetSessionToolsOptions,
  // Personality extensions
  SignificantMoment,
  SignificantMomentsResponse,
  PersonalityShift,
  RecentShiftsResponse,
  UserPersonalityOverlay,
  UserOverlaysListResponse,
  UserOverlayDetailResponse,
  UserOverlayOptions,
  // Fact history
  FactHistoryResponse,
  // Time machine
  TimeMachineOptions,
  TimeMachineMoodSnapshot,
  TimeMachineResponse,
  // Agent status
  SetStatusOptions,
  SetStatusResponse,
  // Capabilities
  AgentCapabilities,
  UpdateCapabilitiesOptions,
  // Custom tools
  CustomToolDefinition,
  CustomToolListResponse,
  CreateCustomToolOptions,
  UpdateCustomToolOptions,
  // Consolidation
  ConsolidateOptions,
  ConsolidateResponse,
  // Summaries
  SummariesOptions,
  MemorySummary,
  SummariesResponse,
  // Project association
  UpdateProjectOptions,
  UpdateProjectResponse,
  // Instance update
  UpdateInstanceOptions,
  // Knowledge Base
  KBDocument,
  KBDocumentListResponse,
  KBNode,
  KBNodeListResponse,
  KBEdge,
  KBNodeHistory,
  KBNodeDetailResponse,
  KBNodeHistoryResponse,
  KBRelatedNode,
  KBSearchResult,
  KBSearchResponse,
  KBSearchOptions,
  KBSchemaField,
  KBSimilarityConfig,
  KBEntitySchema,
  KBSchemaListResponse,
  KBStats,
  InsertFactEntry,
  InsertRelEntry,
  InsertFactsOptions,
  InsertFactDetail,
  InsertFactsResponse,
  CreateSchemaOptions,
  KBAnalyticsRule,
  KBAnalyticsRuleListResponse,
  CreateAnalyticsRuleOptions,
  UpdateAnalyticsRuleOptions,
  KBRecommendationScore,
  KBRecommendationsResponse,
  KBTrendAggregation,
  KBTrendsResponse,
  KBTrendRanking,
  KBTrendRankingsResponse,
  KBConversionStats,
  KBConversionsResponse,
  RecordFeedbackOptions,
  // User Priming
  PrimeUserMetadata,
  PrimeContentBlock,
  PrimeUserOptions,
  PrimeUserResponse,
  AddContentOptions,
  AddContentResponse,
  UserPrimingMetadata,
  UpdateMetadataOptions,
  UpdateMetadataResponse,
  BatchImportUser,
  BatchImportOptions,
  BatchImportResponse,
  ImportJob,
  ImportJobListResponse,
  StructuredColumnMapping,
  StructuredImportSpec,
  // Inventory
  InventoryUpdateOptions,
  InventoryUpdateResponse,
  KBResolutionInfo,
  KBCandidate,
  InventoryQueryOptions,
  InventoryQueryResponse,
  InventoryItem,
  InventoryGroupResult,
  InventoryBatchItem,
  InventoryBatchImportOptions,
  InventoryBatchImportResponse,
  InventoryDirectUpdateOptions,
  InventoryDirectUpdateResponse,
  ListAllFactsOptions,
  ListAllFactsResponse,
  StoredFact,
  // KB Bulk Update
  KBBulkUpdateEntry,
  KBBulkUpdateOptions,
  KBBulkUpdateResponse,
} from "./types.js";
